// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmfDZHw6F_RXYuZ4zyQIMtGYYVhVWZ5XM',
    appId: '1:650242887825:web:4f5774b866e8d80ff4af30',
    messagingSenderId: '650242887825',
    projectId: 'tracknstack-4c50e',
    authDomain: 'tracknstack-4c50e.firebaseapp.com',
    storageBucket: 'tracknstack-4c50e.firebasestorage.app',
    measurementId: 'G-0Z8CC6LFRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV-m5o8UVkM3fjPBzmt0lFBRHkl06XCNU',
    appId: '1:650242887825:android:01a644f6573a0e43f4af30',
    messagingSenderId: '650242887825',
    projectId: 'tracknstack-4c50e',
    storageBucket: 'tracknstack-4c50e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHltZI9H6reKeeNcMlL7k_Sx3FNzwdRoM',
    appId: '1:650242887825:ios:0738e1ba0ac82f35f4af30',
    messagingSenderId: '650242887825',
    projectId: 'tracknstack-4c50e',
    storageBucket: 'tracknstack-4c50e.firebasestorage.app',
    iosBundleId: 'com.example.tracknstack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHltZI9H6reKeeNcMlL7k_Sx3FNzwdRoM',
    appId: '1:650242887825:ios:0738e1ba0ac82f35f4af30',
    messagingSenderId: '650242887825',
    projectId: 'tracknstack-4c50e',
    storageBucket: 'tracknstack-4c50e.firebasestorage.app',
    iosBundleId: 'com.example.tracknstack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmfDZHw6F_RXYuZ4zyQIMtGYYVhVWZ5XM',
    appId: '1:650242887825:web:e0013d0c12b55bccf4af30',
    messagingSenderId: '650242887825',
    projectId: 'tracknstack-4c50e',
    authDomain: 'tracknstack-4c50e.firebaseapp.com',
    storageBucket: 'tracknstack-4c50e.firebasestorage.app',
    measurementId: 'G-3RHLZ3NVLJ',
  );
}
